# Generated by Django 5.1.3 on 2024-11-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Herramienta')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentabancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('banco', models.CharField(blank=True, choices=[('CAIXA', 'Caixa'), ('BBVA', 'BBVA'), ('UNICAJA', 'Unicaja'), ('ING', 'ING')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria_cliente', to='examen.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='herramienta',
            field=models.ManyToManyField(related_name='cliente_herramienta', to='examen.herramienta'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha_votacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_cliente', to='examen.cliente')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_herramienta', to='examen.herramienta')),
            ],
        ),
    ]
